# Stage 1: Builder
FROM node:22-alpine AS builder

WORKDIR /app
COPY frontend/package*.json ./
COPY frontend/prisma ./prisma/

RUN npm ci
COPY ./frontend .
RUN npm run build

# Stage 2: Runner
FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma

RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "start"]